"""Tests for the drone_files MCP tool.

drone_files returns the content of all files generated by a drone job,
read directly from the worktree. Eliminates the need to manually navigate
to worktree paths after drone_wait returns ready.
"""

import json
import threading
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from shepherd_mcp.jobs import store, JobStatus, DroneJob


def _make_job(tmp_path: Path, files: dict[str, str], status: JobStatus = JobStatus.READY) -> DroneJob:
    """Create a job with a real worktree containing the given files."""
    job = store.create(spec="test spec", model="test-model", project_path=str(tmp_path))
    wt = tmp_path / "worktree"
    wt.mkdir()
    for rel_path, content in files.items():
        target = wt / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    job.worktree_path = str(wt)
    job.files = files
    job.status = status
    return job


def _call_drone_files(job_id: str) -> dict:
    """Import and call the drone_files function directly."""
    from shepherd_mcp.server import drone_files
    result = drone_files(job_id)
    return json.loads(result)


def test_returns_file_contents(tmp_path):
    """drone_files returns file paths and their content for a ready job."""
    job = _make_job(tmp_path, {
        "shepherd_mcp/rate_limiter.py": "class RateLimiter:\n    pass\n",
    })
    result = _call_drone_files(job.job_id)
    assert result["job_id"] == job.job_id
    assert "shepherd_mcp/rate_limiter.py" in result["files"]
    assert "RateLimiter" in result["files"]["shepherd_mcp/rate_limiter.py"]


def test_returns_multiple_files(tmp_path):
    """drone_files returns all files when multiple were generated."""
    job = _make_job(tmp_path, {
        "foo.py": "x = 1\n",
        "bar/baz.py": "y = 2\n",
    })
    result = _call_drone_files(job.job_id)
    assert len(result["files"]) == 2
    assert "foo.py" in result["files"]
    assert "bar/baz.py" in result["files"]


def test_works_for_failed_jobs(tmp_path):
    """drone_files works for failed jobs that have partial worktree content."""
    job = _make_job(tmp_path, {"partial.py": "# incomplete\n"}, status=JobStatus.FAILED)
    result = _call_drone_files(job.job_id)
    assert "partial.py" in result["files"]


def test_unknown_job_id_returns_error():
    """drone_files returns an error for an unknown job_id."""
    result = _call_drone_files("00000000-0000-0000-0000-000000000000")
    assert "error" in result


def test_no_worktree_returns_error(tmp_path):
    """drone_files returns an error if the job has no worktree."""
    job = store.create(spec="test", model="test-model", project_path=str(tmp_path))
    job.status = JobStatus.READY
    job.files = {"foo.py": "x = 1\n"}
    # worktree_path is None — no worktree was created
    result = _call_drone_files(job.job_id)
    assert "error" in result


def test_missing_file_returns_error_for_that_file(tmp_path):
    """If a file in job.files is missing from disk, its content is an error string."""
    job = _make_job(tmp_path, {"exists.py": "x = 1\n"})
    # Simulate a file listed in job.files but missing from disk
    job.files["missing.py"] = "# was here"
    result = _call_drone_files(job.job_id)
    assert "exists.py" in result["files"]
    assert "error" in result["files"]["missing.py"].lower() or "not found" in result["files"]["missing.py"].lower()
